name: Build Web App
 
on: [push]
 
jobs:
  job_1:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.2
      
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore SharpDevelopWebApi/SharpDevelopWebApi.sln       
 
    - name: Build and Publish Web App
      run: msbuild SharpDevelopWebApi/SharpDevelopWebApi.sln
    
    - name: Copy to Publish folder
      run: |       
       mkdir -p publish
       cp -R SharpDevelopWebApi/bin/ ./publish  
       cp -R SharpDevelopWebApi/App_Data/ ./publish 
       cp SharpDevelopWebApi/Global.asax ./publish 
       cp SharpDevelopWebApi/web.config ./publish 
       cp SharpDevelopWebApi/index.html ./publish 
       
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: publish/    

  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 2
      
    - name: Download Artifact
      uses: actions/download-artifact@v2  
    
    # To add a secret go to the Settings tab in your Github project then select Secrets
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
       ftp-server: ftp://bernardgabon.somee.com/www.bernardgabon.somee.com/
       ftp-username: bernardgabon
       ftp-password: ${{ secrets.SOMEE_PASSWORD }}
       local-dir: publish/
       git-ftp-args: --insecure

    - name: Ping my site
      uses: Leocardoso94/is-my-site-up@v1.2
      with:
       site: www.bernardgabon.somee.com
