name: Build Web App
 
on: [push]
jobs:
   job_2:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      
    - name: List output files
      working-directory: ./published_webapp
      run: ls
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: "ftp://bernardgabon.somee.com"
        ftp-username: "bernardgabon"
        ftp-password: "sds123..."
        git-ftp-args: --remote-root www.bernardgabon.somee.com
   
