name: Build Web App
 
on: [push]
 
jobs:
  job_1:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore SharpDevelopWebApi/SharpDevelopWebApi.sln
 
    - name: Build and Publish Web App
      run: msbuild SharpDevelopWebApi/SharpDevelopWebApi.sln
    
    - name: Create Publish dir
      run: | 
       mkdir -p publish
       cp -R SharpDevelopWebApi/bin/ ./publish  
       cp -R SharpDevelopWebApi/App_Data/ ./publish 
       cp SharpDevelopWebApi/Global.asax ./publish 
       cp SharpDevelopWebApi/web.config ./publish 
       
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: publish\    

  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      
    - name: List output files
      run: ls
      
    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
      with:
        ftp_host: "ftp://bernardgabon.somee.com"
        ftp_username: "bernardgabon"
        ftp_password: "sds123..."
        local_source_dir: "publish"
        dist_target_dir: "www.bernardgabon.somee.com"
      
    #- name: FTP Deploy
      #uses: SamKirkland/FTP-Deploy-Action@3.1.1
      #with:
        #ftp-server: "ftp://bernardgabon.somee.com/www.bernardgabon.somee.com/"
        #ftp-username: "bernardgabon"
        #ftp-password: "sds123..."
        #local-dir: publish
        #git-ftp-args: --insecure
