name: Build Web App
 
on: [push]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore SharpDevelopWebApi/SharpDevelopWebApi.sln
 
    - name: Build and Publish Web App
      run: msbuild SharpDevelopWebApi/SharpDevelopWebApi.sln 
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: SharpDevelopWebApi\bin\        
      
    - name: List output files
      working-directory: ./SharpDevelopWebApi
      run: ls
      
    - name: Simple FTP deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
      with:
       ftp_host: ftp://bernardgabon.somee.com
       ftp_username: bernardgabon
       ftp_password: sds123...
       local_source_dir: "bin"
